var searchData=
[
  ['tag_5finvoke_5ffn_0',['tag_invoke_fn',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/structguanaqo_1_1tag__invoke__fn__ns_1_1tag__invoke__fn.html',1,'guanaqo::tag_invoke_fn_ns']]],
  ['tail_1',['Tail',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['tail_3c_20types_3c_20t_2c_20ts_2e_2e_2e_20_3e_20_3e_2',['Tail&lt; Types&lt; T, Ts... &gt; &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['template_20matrix_3c_20t_2c_20order_20_3e_3',['template matrix&lt; T, Order &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1simd__view__types.html',1,'batmat::linalg']]],
  ['template_20view_3c_20const_20real_5ft_2c_20order_20_3e_4',['template view&lt; const real_t, Order &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1simd__view__types.html',1,'batmat::linalg']]],
  ['template_20view_3c_20real_5ft_2c_20order_20_3e_5',['template view&lt; real_t, Order &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1simd__view__types.html',1,'batmat::linalg']]],
  ['template_20view_3c_20t_2c_20order_20_3e_6',['template view&lt; T, Order &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1simd__view__types.html',1,'batmat::linalg']]],
  ['thread_5fpool_7',['thread_pool',['https://tttapa.github.io/batmat/0.0.18/Doxygen/classbatmat_1_1thread__pool.html',1,'batmat']]],
  ['threadperfcounters_8',['ThreadPerfCounters',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/group__trace__pcm.html',1,'guanaqo::pcm']]],
  ['tilingoptions_9',['TilingOptions',['https://tttapa.github.io/batmat/0.0.18/Doxygen/group__topic-linalg.html',1,'batmat::linalg']]],
  ['timed_10',['Timed',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/group__timing.html',1,'guanaqo']]],
  ['timed_3c_20batmat_3a_3adefaulttimings_20_3e_11',['Timed&lt; batmat::DefaultTimings &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structguanaqo_1_1Timed_3_01batmat_1_1DefaultTimings_01_4.html',1,'guanaqo']]],
  ['timed_3c_20std_3a_3achrono_3a_3aduration_3c_20rep_2c_20period_20_3e_20_3e_12',['Timed&lt; std::chrono::duration&lt; Rep, Period &gt; &gt;',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/structguanaqo_1_1Timed_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_01_4.html',1,'guanaqo']]],
  ['timed_3c_20timingscpu_20_3e_13',['Timed&lt; TimingsCPU &gt;',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/structguanaqo_1_1Timed_3_01TimingsCPU_01_4.html',1,'guanaqo']]],
  ['timings_14',['Timings',['../structcyqlone_1_1qpalm_1_1CyQPALMBackend.html#structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1Timings',1,'cyqlone::qpalm::CyQPALMBackend']]],
  ['timingscpu_15',['TimingsCPU',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/group__timing.html',1,'guanaqo']]],
  ['tracelogger_16',['TraceLogger',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/structguanaqo_1_1TraceLogger.html',1,'guanaqo']]],
  ['track_5fzeros_5ft_17',['track_zeros_t',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1track__zeros__t.html',1,'batmat::linalg']]],
  ['treebarrier_18',['TreeBarrier',['../classcyqlone_1_1TreeBarrier.html',1,'cyqlone']]],
  ['treebarrier_3c_20completion_5ftype_2c_20uint16_5ft_20_3e_19',['TreeBarrier&lt; completion_type, uint16_t &gt;',['../classcyqlone_1_1TreeBarrier.html',1,'cyqlone']]],
  ['triangular_5faccessor_20',['triangular_accessor',['https://tttapa.github.io/batmat/0.0.18/Doxygen/structbatmat_1_1linalg_1_1micro__kernels_1_1hyhound_1_1triangular__accessor.html',1,'batmat::linalg::micro_kernels::hyhound']]],
  ['tricyqleparams_21',['TricyqleParams',['../group__topic-block-tridiag-solvers.html#structcyqlone_1_1TricyqleParams',1,'cyqlone']]],
  ['tricyqleparams_3c_20real_5ft_20_3e_22',['TricyqleParams&lt; real_t &gt;',['../namespacecyqlone.html#group__topic-block-tridiag-solvers',1,'cyqlone']]],
  ['tricyqleparams_3c_20value_5ftype_20_3e_23',['TricyqleParams&lt; value_type &gt;',['../namespacecyqlone.html#group__topic-block-tridiag-solvers',1,'cyqlone']]],
  ['tricyqlesolver_24',['TricyqleSolver',['../structcyqlone_1_1TricyqleSolver.html',1,'cyqlone']]],
  ['tricyqlesolver_3c_204_2c_20real_5ft_2c_20storageorder_3a_3acolmajor_2c_20parallel_3a_3acontext_3c_3e_20_3e_25',['TricyqleSolver&lt; 4, real_t, StorageOrder::ColMajor, parallel::Context&lt;&gt; &gt;',['../structcyqlone_1_1TricyqleSolver.html',1,'cyqlone']]],
  ['tricyqlesolver_3c_20v_2c_20real_5ft_20_3e_26',['TricyqleSolver&lt; v, real_t &gt;',['../structcyqlone_1_1TricyqleSolver.html',1,'cyqlone']]],
  ['tricyqlesolver_3c_20vl_2c_20t_2c_20defaultorder_2c_20ctx_20_3e_27',['TricyqleSolver&lt; VL, T, DefaultOrder, Ctx &gt;',['../structcyqlone_1_1TricyqleSolver.html',1,'cyqlone']]],
  ['tridiagsystem_28',['TridiagSystem',['../solve-block-tridiagonal_8cpp.html#structTridiagSystem',1,'']]],
  ['type_29',['type',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types::type&lt;&gt;'],['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types::type&lt;&gt;'],['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/namespaceguanaqo_1_1linalg_1_1sparsity_1_1detail.html',1,'guanaqo::linalg::sparsity::detail::type&lt; To, SparsityVariant &gt;']]],
  ['type_5fcaster_3c_20guanaqo_3a_3amatrixview_3c_20t_2c_20i_2c_20s_2c_20o_20_3e_20_3e_30',['type_caster&lt; guanaqo::MatrixView&lt; T, I, S, O &gt; &gt;',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/structnanobind_1_1detail_1_1type__caster_3_01guanaqo_1_1MatrixView_3_01T_00_01I_00_01S_00_01O_01_4_01_4.html',1,'nanobind::detail']]],
  ['typeerased_31',['TypeErased',['https://tttapa.github.io/guanaqo/1.0.0-alpha.25/Doxygen/classguanaqo_1_1TypeErased.html',1,'guanaqo']]],
  ['types_32',['Types',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['types_3c_20func_3c_20ts_20_3e_2e_2e_2e_20_3e_33',['Types&lt; Func&lt; Ts &gt;... &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['types_3c_20t_20_3e_34',['Types&lt; T &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['types_3c_20ts_2e_2e_2e_20_3e_35',['Types&lt; Ts... &gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]],
  ['types_3c_3e_36',['Types&lt;&gt;',['https://tttapa.github.io/batmat/0.0.18/Doxygen/namespacebatmat_1_1types.html',1,'batmat::types']]]
];
