import sys
import numpy as np
import numpy.linalg as la
from scipy.io import loadmat

# Load the data generated by solve-block-tridiagonal.cpp
data = loadmat("block_tridiagonal_system.mat")
# Data is stored in Fortran order, so transpose
M = np.moveaxis(data["M"], -1, 0)  # (n, n, N) -> (N, n, n)
K = np.moveaxis(data["K"], -1, 0)  # (n, n, N) -> (N, n, n)
b = np.moveaxis(data["b"], -1, 0)  # (n, 1, N) -> (N, n, 1)
x = np.moveaxis(data["x"], -1, 0)  # (n, 1, N) -> (N, n, 1)
N, n, _ = M.shape

# Construct the full block tridiagonal system as a dense matrix for verification
A = np.zeros((N * n, N * n))
for i in range(N):
    A[i * n : (i + 1) * n, i * n : (i + 1) * n] = np.tril(M[i]) + np.tril(M[i], -1).T
    A[((i + 1) % N) * n : ((i + 1) % N + 1) * n, i * n : (i + 1) * n] = K[i]
    A[i * n : (i + 1) * n, ((i + 1) % N) * n : ((i + 1) % N + 1) * n] = K[i].T

# Report the condition number and the residual of the solution
print(f"Number of blocks:    {N}")
print(f"Block size:          {n}")
print(f"Number of nonzeros:  {N * n * (n + 1) // 2 + N * n * n}")
condA = la.cond(A)
print(f"Condition number κ(A):     {condA:.17e}")
res = la.norm(A @ x.ravel() - b.ravel()) / la.norm(b.ravel())
print(f"Residual ‖Ax-b‖/‖b‖:       {res:.17e}")
print(f"Scaled κ(A)⁻¹ ‖Ax-b‖/‖b‖:  {res / condA:.17e}")

sys.exit(0 if res < 1e-12 * condA else 1)
