var hierarchy =
[
    [ "cyqlone::CyqloneParams&lt; T &gt;", "group__topic-ocp-solvers.html#structcyqlone_1_1CyqloneParams", null ],
    [ "cyqlone::CyqloneSolver&lt; VL, T, DefaultOrder, Ctx &gt;", "structcyqlone_1_1CyqloneSolver.html", null ],
    [ "cyqlone::CyqloneStorage&lt; T &gt;", "structcyqlone_1_1CyqloneStorage.html", null ],
    [ "cyqlone::EmptyCompletion", "structcyqlone_1_1EmptyCompletion.html", null ],
    [ "cyqlone::LinearOCPSparseQP", "structcyqlone_1_1LinearOCPSparseQP.html", null ],
    [ "cyqlone::LinearOCPSparseQP::KKTMatrix", "structcyqlone_1_1LinearOCPSparseQP.html#structcyqlone_1_1LinearOCPSparseQP_1_1KKTMatrix", null ],
    [ "cyqlone::LinearOCPStorage", "structcyqlone_1_1LinearOCPStorage.html", null ],
    [ "cyqlone::LinearOCPStorage::KKTError", "structcyqlone_1_1LinearOCPStorage.html#structcyqlone_1_1LinearOCPStorage_1_1KKTError", null ],
    [ "cyqlone::LinearOCPStorage::Solution", "structcyqlone_1_1LinearOCPStorage_1_1Solution.html", null ],
    [ "cyqlone::matio_traits&lt; T &gt;", "namespacecyqlone.html#structcyqlone_1_1matio__traits", null ],
    [ "cyqlone::matio_traits&lt; double &gt;", "structcyqlone_1_1matio__traits_3_01double_01_4.html", null ],
    [ "cyqlone::matio_traits&lt; float &gt;", "structcyqlone_1_1matio__traits_3_01float_01_4.html", null ],
    [ "cyqlone::matio_traits&lt; I &gt;", "structcyqlone_1_1matio__traits_3_01I_01_4.html", null ],
    [ "cyqlone::NeumaierSum&lt; T &gt;", "classcyqlone_1_1NeumaierSum.html", null ],
    [ "cyqlone::norms&lt; T, simd &gt;", "structcyqlone_1_1norms.html", null ],
    [ "cyqlone::norms&lt; T, simd &gt;::result_simd", "structcyqlone_1_1norms.html#structcyqlone_1_1norms_1_1result__simd", null ],
    [ "cyqlone::norms&lt; T, void &gt;", "structcyqlone_1_1norms_3_01T_00_01void_01_4.html", null ],
    [ "cyqlone::norms&lt; T, void &gt;::result", "structcyqlone_1_1norms_3_01T_00_01void_01_4_1_1result.html", null ],
    [ "cyqlone::OCPDim", "structcyqlone_1_1OCPDim.html", null ],
    [ "cyqlone::parallel::Context&lt; SC &gt;", "structcyqlone_1_1parallel_1_1Context.html", null ],
    [ "cyqlone::parallel::SharedContext", "structcyqlone_1_1parallel_1_1SharedContext.html", null ],
    [ "cyqlone::PCRFactorTest&lt; VL, T, DefaultOrder &gt;", "structcyqlone_1_1PCRFactorTest.html", null ],
    [ "cyqlone::qpalm::ABSums", "structcyqlone_1_1qpalm_1_1ABSums.html", null ],
    [ "cyqlone::qpalm::Breakpoint", "structcyqlone_1_1qpalm_1_1Breakpoint.html", null ],
    [ "cyqlone::qpalm::BreakpointsResult", "namespacecyqlone_1_1qpalm.html#structcyqlone_1_1qpalm_1_1BreakpointsResult", null ],
    [ "cyqlone::qpalm::compute_breakpoints_fn", "structcyqlone_1_1qpalm_1_1compute__breakpoints__fn.html", null ],
    [ "cyqlone::qpalm::CyqloneData", "group__topic-optimization-solvers-ocp.html#structcyqlone_1_1qpalm_1_1CyqloneData", null ],
    [ "cyqlone::qpalm::CyQPALMBackend&lt; VL, DefaultOrder &gt;", "structcyqlone_1_1qpalm_1_1CyQPALMBackend.html", null ],
    [ "cyqlone::qpalm::CyQPALMBackend&lt; VL, DefaultOrder &gt;::PenaltySettings", "structcyqlone_1_1qpalm_1_1CyQPALMBackend.html#structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1PenaltySettings", null ],
    [ "cyqlone::qpalm::CyQPALMBackend&lt; VL, DefaultOrder &gt;::Timings", "structcyqlone_1_1qpalm_1_1CyQPALMBackend.html#structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1Timings", null ],
    [ "cyqlone::qpalm::CyQPALMBackendSettings", "group__topic-optimization-solvers-ocp.html#structcyqlone_1_1qpalm_1_1CyQPALMBackendSettings", null ],
    [ "cyqlone::qpalm::CyQPALMBackendStats", "group__topic-optimization-solvers-ocp.html#structcyqlone_1_1qpalm_1_1CyQPALMBackendStats", null ],
    [ "cyqlone::qpalm::detail::backend_stats_type&lt; T &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__stats__type", null ],
    [ "cyqlone::qpalm::detail::backend_stats_type&lt; CyQPALMBackend&lt; VL, DefaultOrder &gt; &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__stats__type_3_01CyQPALMBackend_3_01VL_00_01DefaultOrder_01_4_01_4", null ],
    [ "cyqlone::qpalm::detail::backend_type&lt; T &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__type", null ],
    [ "cyqlone::qpalm::detail::backend_type&lt; std::unique_ptr&lt; T, D &gt; &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__type_3_01std_1_1unique__ptr_3_01T_00_01D_01_4_01_4", null ],
    [ "cyqlone::qpalm::detail::backend_type&lt; T * &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__type_3_01T_01_5_01_4", null ],
    [ "cyqlone::qpalm::detail::backend_type&lt; unique_CyQPALMBackend&lt; VL, DefaultOrder &gt; &gt;", "namespacecyqlone_1_1qpalm_1_1detail.html#structcyqlone_1_1qpalm_1_1detail_1_1backend__type_3_01unique__CyQPALMBackend_3_01VL_00_01DefaultOrder_01_4_01_4", null ],
    [ "cyqlone::qpalm::DetailedStats", "structcyqlone_1_1qpalm_1_1DetailedStats.html", null ],
    [ "cyqlone::qpalm::DetailedStats::Entry", "structcyqlone_1_1qpalm_1_1DetailedStats.html#structcyqlone_1_1qpalm_1_1DetailedStats_1_1Entry", null ],
    [ "cyqlone::qpalm::get_breakpoints_fn", "structcyqlone_1_1qpalm_1_1get__breakpoints__fn.html", null ],
    [ "cyqlone::qpalm::get_partitioned_breakpoints_fn", "structcyqlone_1_1qpalm_1_1get__partitioned__breakpoints__fn.html", null ],
    [ "cyqlone::qpalm::LineSearch&lt; Vec &gt;", "structcyqlone_1_1qpalm_1_1LineSearch.html", null ],
    [ "cyqlone::qpalm::LineSearch&lt; Vec &gt;::Result", "structcyqlone_1_1qpalm_1_1LineSearch.html#structcyqlone_1_1qpalm_1_1LineSearch_1_1Result", null ],
    [ "cyqlone::qpalm::LineSearchSettings", "namespacecyqlone_1_1qpalm.html#structcyqlone_1_1qpalm_1_1LineSearchSettings", null ],
    [ "cyqlone::qpalm::PartitionedBreakpoints", "namespacecyqlone_1_1qpalm.html#structcyqlone_1_1qpalm_1_1PartitionedBreakpoints", null ],
    [ "cyqlone::qpalm::problems::PlatooningParams", "namespacecyqlone_1_1qpalm_1_1problems.html#structcyqlone_1_1qpalm_1_1problems_1_1PlatooningParams", null ],
    [ "cyqlone::qpalm::problems::PlatooningProblem", "namespacecyqlone_1_1qpalm_1_1problems.html#structcyqlone_1_1qpalm_1_1problems_1_1PlatooningProblem", null ],
    [ "cyqlone::qpalm::problems::SpringMassParams", "structcyqlone_1_1qpalm_1_1problems_1_1SpringMassParams.html", null ],
    [ "cyqlone::qpalm::problems::SpringMassProblem", "namespacecyqlone_1_1qpalm_1_1problems.html#structcyqlone_1_1qpalm_1_1problems_1_1SpringMassProblem", null ],
    [ "cyqlone::qpalm::Settings", "structcyqlone_1_1qpalm_1_1Settings.html", null ],
    [ "cyqlone::qpalm::Solver&lt; Backend &gt;", "classcyqlone_1_1qpalm_1_1Solver.html", null ],
    [ "cyqlone::qpalm::SolverImplementation&lt; Backend &gt;", "structcyqlone_1_1qpalm_1_1SolverImplementation.html", null ],
    [ "cyqlone::qpalm::SolverStats", "group__topic-optimization-solvers.html#structcyqlone_1_1qpalm_1_1SolverStats", null ],
    [ "cyqlone::qpalm::SolverTimings", "structcyqlone_1_1qpalm_1_1SolverTimings.html", null ],
    [ "cyqlone::SparseCOO&lt; class Index &gt;", "structcyqlone_1_1SparseCOO.html", null ],
    [ "cyqlone::SparseCSC&lt; class Index, class StorageIndex &gt;", "structcyqlone_1_1SparseCSC.html", null ],
    [ "cyqlone::SparseMatrix", "structcyqlone_1_1SparseMatrix.html", null ],
    [ "cyqlone::SparseMatrixBuilder", "structcyqlone_1_1SparseMatrixBuilder.html", null ],
    [ "cyqlone::TreeBarrier&lt; CompletionFn, PhaseType &gt;", "classcyqlone_1_1TreeBarrier.html", null ],
    [ "cyqlone::TreeBarrier&lt; CompletionFn, PhaseType &gt;::arrival_token", "classcyqlone_1_1TreeBarrier_1_1arrival__token.html", [
      [ "cyqlone::TreeBarrier< CompletionFn, PhaseType >::arrival_token_typed< T >", "classcyqlone_1_1TreeBarrier_1_1arrival__token__typed.html", null ]
    ] ],
    [ "cyqlone::TreeBarrier&lt; CompletionFn, PhaseType &gt;::State", "structcyqlone_1_1TreeBarrier_1_1State.html", null ],
    [ "cyqlone::TreeBarrier&lt; CompletionFn, PhaseType &gt;::Storage", "structcyqlone_1_1TreeBarrier_1_1Storage.html", null ],
    [ "cyqlone::TricyqleParams&lt; T &gt;", "group__topic-block-tridiag-solvers.html#structcyqlone_1_1TricyqleParams", null ],
    [ "cyqlone::TricyqleSolver&lt; VL, T, DefaultOrder, Ctx &gt;", "structcyqlone_1_1TricyqleSolver.html", null ],
    [ "Options", "benchmarks_2cyqpalm_2spring-mass_8cpp.html#structOptions", null ],
    [ "Problem", "benchmarks_2cyqpalm_2spring-mass_8cpp.html#structProblem", null ],
    [ "Solver", "structSolver.html", null ],
    [ "SpringMassParams", "structSpringMassParams.html", null ],
    [ "std::unique_ptr&lt; T &gt;", null, [
      [ "cyqlone::qpalm::unique_CyQPALMBackend< VL, DefaultOrder >", "structcyqlone_1_1qpalm_1_1unique__CyQPALMBackend.html", null ]
    ] ],
    [ "storage_t", null, [
      [ "cyqlone::qpalm::CyQPALMBackend< VL, DefaultOrder >::active_set_t", "structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1active__set__t.html", null ],
      [ "cyqlone::qpalm::CyQPALMBackend< VL, DefaultOrder >::eq_constr_vec_t", "structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1eq__constr__vec__t.html", null ],
      [ "cyqlone::qpalm::CyQPALMBackend< VL, DefaultOrder >::ineq_constr_vec_t", "structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1ineq__constr__vec__t.html", null ],
      [ "cyqlone::qpalm::CyQPALMBackend< VL, DefaultOrder >::var_vec_t", "structcyqlone_1_1qpalm_1_1CyQPALMBackend_1_1var__vec__t.html", null ]
    ] ],
    [ "TridiagSystem", "solve-block-tridiagonal_8cpp.html#structTridiagSystem", null ]
];