name: 'CI: Linux'
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: "Build (GCC ${{ matrix.gcc }}, ${{ matrix.build_type }}, ${{ matrix.profile }})"
    strategy:
      matrix:
        gcc: ["15"]
        build_type: ["Debug"]
        profile: ["ci"]
      fail-fast: false
    runs-on: ubuntu-24.04
    env:
      CTEST_OUTPUT_ON_FAILURE: "1"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan and sccache
      uses: ./.github/workflows/setup-conan
      with:
        cache-key: ${{ matrix.profile }}-${{ matrix.gcc }}-${{ matrix.build_type }}

    - name: Build
      run: >
        conan create . --build=missing -pr scripts/ci/profiles/${{ matrix.profile }}.profile
        -s compiler.version=${{ matrix.gcc }}
        -s build_type=${{ matrix.build_type }}
        -s:b compiler.cppstd=20

    - run: conan cache clean
